config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  resources :donations
  resources :pledges
  resources :carts
  resources :notes
  get 'charity/index'

  get 'user/:id/profile' => 'user#profile', as: :profile
  get 'user/:id/project' => 'user#project', as: :user_project
  get 'user/:id/donation' => 'user#donation', as: :user_donation

  resources :projects, param: :slug do
    member do
     post 'like'
     get 'who_donated'
    end
  end

    namespace :api do
      namespace :v1 do
        resources :items, only: [:index, :create, :destroy, :update]
      end
    end

  namespace :admin do
   resources :users, except: [:new, :create]
   resources :projects, param: :slug, except: [:new, :create]
   resources :projects, only: [:archive, :unarchive] do
    post :archive
    post :unarchive
    post :faeture
    post :unfaeture
    post :watched
    post :unwatched
  end
  end

    root 'charity#index', as: 'charity'

end

app/models/project.rb
class Project < ActiveRecord::Base

   STATES = ["closed", "open"]

 belongs_to :user
 has_many :likes
 has_many :pledges
 has_many :donations, through: :pledges
 before_destroy :ensure_not_referenced_by_any_pledge

 validates :title, :description, :contact_email, presence: true
 validates :estimate, numericality: {greater_than_or_equal_to: 0.01}
 validates :title, uniqueness: true
 #validates :image_url, allow_blank: true, format: {
 # with: %r{\.(gif|jpg|png)\Z}i,
  #message: 'must be a URL for GIF, JPG or PNG image.'
 #} 
  validate :picture_size
  validates :slug, presence: true, uniqueness: true

  #serialize :custom_fields, Array

  scope :recent, -> { order('title ASC') }
  scope :live, -> { where("state = 'open' and (closes_at is null or closes_at > ?)", Time.current).order('closes_at ASC') }
  scope :top_featured, -> { where(featured: true) }
  scope :top_watched, -> { where(watch: true) }
 

  before_validation :generate_slug
  before_save :update_closes_at_if_manually_closed

  mount_uploader :picture, PictureUploader


  def self.latest
   Project.order(:updated_at).last
  end 

  def thumbs_up_total
    self.likes.where(like: true).size
  end
  def thumbs_down_total
    self.likes.where(like: false).size
  end

  def custom_fields_string=(custom_fields_string)
   self.custom_fields = self.custom_fields_string_to_array(custom_fields_string)
  end
  def custom_fields_string_to_array(string)
    (string || '').split(',').map(&:strip).reject(&:blank?).uniq
  end
  def custom_fields_string
    custom_fields.join(',')
  end

  def to_param
     slug
  end
  
  def generate_slug
    self.slug = title.parameterize if slug.blank?
  end

  def to_s
    title
  end

   def open?
     state == 'open' && (closes_at.nil? || closes_at > Time.current)
   end

   def close?
     !open?
   end

   def past_open?
     state == 'open' && closes_at < Time.current
   end

   def unmet_requirements_for_scheduling
     missing_prereqs = []

     missing_prereqs << "Project must have a start date" unless start_date
     missing_prereqs << "Project must have a end date" unless end_date

     missing_prereqs
   end

   def archive
     if current?
        update_attribute(:archived, true)
     end
   end
  
   def unarchive
     if archived?
        update_attribute(:archived, false)
     end
   end

   def faeture
     if not_priority?
        update_attribute(:featured, true)
     end
   end

   def unfaeture
     if featured?
        update_attribute(:featured, false)
     end
   end

   def not_priority?
     !featured?
   end

  def current?
    !archived?
  end

  def interesting?
    !watch?
  end
  def watched
    if interesting?
      update_attribute(:watch, true)
    end
  end
  def unwatched
    if watch?
      update_attribute(:watch, false)
    end
  end

  def donation_opens
    opens_at && opens_at.to_s(:long_with_zone)
  end
  def donation_closes
   closes_at && closes_at.to_s(:long_with_zone)
  end

   def fundraising_date(fundraising_day)
     start_date + (fundraising_day - 1).days
   end
  

  private

  # ensure that there are no line items referencing this product
  def ensure_not_referenced_by_any_pledge
   if pledges.empty?
   return true
   else
   errors.add(:base, 'Pledges are present')
   return false
   end
  end
  
  def picture_size
   if picture.size > 5.megabytes
    errors.add(:picture, "should be less than 5mb")
   end
  end

   def update_closes_at_if_manually_closed
      if changes.key?(:state) && changes[:state] == ['open', 'closed']
        self.closes_at = DateTime.now
      end
   end

end


# == Schema Information
#
#  Table name: projects
#   
#   t.string   "title"
#   t.text     "description"
#   t.decimal  "estimate",    precision: 8, scale: 2
#   t.datetime "created_at",                          null: false
#   t.datetime "updated_at",                          null: false
#   t.integer  "user_id"
#   t.string   "picture"
#   t.string   "slug"
#   t.string   "contact_email"
#   t.string   "state"
#   t.string   "archived",      default(FALSE)    
#   t.text     "review_tags"
#   t.string   "url"
#   t.datetime  "start_date"
#   t.datetime  "end_date"
#   t.text      "custom_fields"
#   t.datetime  "opens_at"
#   t.datetime  "closes_at"
#   t.boolean   "featured"
#   t.boolean   "watch"
#
#add_index "projects", ["user_id"], name: "index_projects_on_user_id", using: :btree
#
#
#
#

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::ApplicationController
  before_filter :require_project, only: [:destroy, :edit, :update, :show]
   
    # GET admin/projects/1/edit
   def edit
   end


    # PATCH/PUT /projects/1
    # PATCH/PUT /projects/1.json
   def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to admin_project_path, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
   end

    def show
      pledge = @project.pledges.includes(:user).recent
      rating_counts = @project.thumbs_up_total
       
      render locals: {
              pledge: pledge,
              rating_counts: rating_counts
            }
    end
   
    # DELETE /projects/1
    # DELETE /projects/1.json
   def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

   def archive
     @project = Project.find_by_id(params[:project_id])
      if @project
        @project.archive
         flash[:alert] = "#{@project.title} is now archived."
         redirect_to :back
      else
        redirect_to admin_projects_path
      end
    end

    def unarchive
      @project = Project.find_by_id(params[:project_id])
        if @project
         @project.unarchive
         flash[:alert] = "#{@project.title} is now current."
      else
        flash[:danger] = "Project not found. Unable to unarchive."
      end
        redirect_to admin_projects_path
    end

   def faeture
     @project = Project.find_by_id(params[:project_id])
      if @project
        @project.faeture
         flash[:alert] = "#{@project.title} is now featured."
         redirect_to :back
      else
        redirect_to admin_projects_path
      end
    end

    def unfaeture
      @project = Project.find_by_id(params[:project_id])
        if @project
         @project.unfaeture
         flash[:alert] = "#{@project.title} is now normal priority."
      else
        flash[:danger] = "Project not found. Unable to unfeature."
      end
        redirect_to admin_projects_path
    end

   def watched
     @project = Project.find_by_id(params[:project_id])
      if @project
        @project.watched
         flash[:alert] = "#{@project.title} is now watched."
         redirect_to :back
      else
        redirect_to admin_projects_path
      end
    end

    def unwatched
      @project = Project.find_by_id(params[:project_id])
        if @project
         @project.unwatched
         flash[:alert] = "#{@project.title} is now normal project."
      else
        flash[:danger] = "Project not found. Unable to unwatched."
      end
        redirect_to admin_projects_path
    end

    def index
     @projects = Project.order('archived').all
    end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  include CurrentCart
  before_action :set_cart
  
  before_action :set_project, only: [:show, :edit, :update, :destroy, :like]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update]
  before_action :require_admin_user, only: [:destroy]

  rescue_from ActiveRecord::RecordNotFound, with: :invalid_path

  # GET /projects
  # GET /projects.json
  def index
    #@projects = Project.all.sort_by{|likes| likes.thumbs_up_total}
     @projects = Project.paginate(page: params[:page], per_page: 2)
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
   respond_to do |format|
    format.html 
    format.js
   end

  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    @project.user = current_user
    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  #def update
   # respond_to do |format|
    #  if @project.update(project_params)
     #   format.html { redirect_to @project, notice: 'Project was successfully updated.' }
      #  format.json { render :show, status: :ok, location: @project }
      #else
       # format.html { render :edit }
        #format.json { render json: @project.errors, status: :unprocessable_entity }
      #end
    #end
  #end

  # DELETE /projects/1
  # DELETE /projects/1.json
  #def destroy
   # @project.destroy
    #respond_to do |format|
     # format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      #format.json { head :no_content }
    #end
  #end

  def who_donated
   @project = Project.find(params[:id])
   @latest_donation = @project.donations.order(:updated_at).last
   if stale?(@latest_donation)
     respond_to do |format|
       format.atom
     end
   end
  end

   def like
     like = Like.create(like: params[:like], user: current_user, project: @project)
     if like.valid?
      flash[:success] = "You like this project"
      redirect_to :back
     else
      flash[:danger] = "You can only vote once"
      redirect_to :back
     end
   end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      #@project = Project.find(params[:id])
      @project = Project.find_by!(slug: params[:slug])
    end
    def require_same_user
      if current_user != @project.user and !current_user.admin?
       flash[:danger] = "You can only edit your project"
       redirect_to projects_path
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    #def project_params
     # params.require(:project).permit(:title, :description, :contact_email, :estimate, :picture, :user, :slug, :url, :start_date, :end_date, :closes_at, :opens_at, :custom_fields, :review_tags, :state)
    #end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= render 'shared/errors', obj: @project %>

  <div class="row projects">
   <div class="well col-md-8 col-md-offset-2">    
     <%= form_for(@project, html: {multipart: true}) do |f| %>
  
   <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: 'Title of the project' %>
   </div>  

    <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control', placeholder: 'Description of the project', rows: 10 %>
    </div>  
     <div class="form-group">
     <%= f.label :contact_email %>
     <%= f.email_field :contact_email, class: 'form-control', placeholder: 'Project\'s Email' %>
     </div>

   <div class="form-group">
    <%= f.label :estimate %>
    <%= f.text_field :estimate, class: 'form-control', placeholder: 'The project estimate' %>
    </div>

   <div class="form-group">
     <%= f.label :slug %>
     <%= f.text_field :slug, class: 'form-control', placeholder: 'Slug for the event URL, maybe left blank' %>
 <p class="help-block">The slug will be used in public facing URLs. If you leave this blank, a slug will be generated based on the title.</p>
  </div>
   <div class="form-group">
     <%= f.label :url %>
     <%= f.text_field :url, class: 'form-control', placeholder: 'Event\'s URL' %>
  </div>
  
   <div class="form-group">
    <span class="picture">
     <%= f.file_field :picture, accept: 'image/jpeg, image/gif, image/png' %>
    </span>
  </div>

   <div class="form-group">
     <%= f.label :start_date %>
     <%= f.object.start_date.to_s(:month_day_year) unless f.object.start_date.blank? %>
     <%= f.text_field :start_date, value: (f.object.start_date.blank? ? "" : f.object.start_date.to_s(:month_day_year) )  %>
  </div>
   <div class="form-group">
     <%= f.label :end_date %>
     <%= f.object.end_date.to_s(:month_day_year) unless f.object.end_date.blank? %>
     <%= f.text_field :end_date, value: (f.object.end_date.blank? ? "" : f.object.end_date.to_s(:month_day_year) )  %>
    <p class="help-block">Open Fundraiser end date is optional. If you do not provide one the Fundraiser will defer to its state.</p>
  </div>

    <%= f.submit(@project.new_record? ? 'Create Project' : 'Edit Project', class: "btn btn-success") %>
  
    <% end %>
   </div>
  </div>

   <script type = "text/javascript">
    $('#project_picture').bind('change', function() {
      size_in_megabytes = this.files[0].size/1024/1024;
      if (size_in_megabytes > 5) {
       alert('Maximum file size is 5mb. Please choose a smaller file');
      }
    });
  </script>

app/views/projects/_show.html.erb
<!-- Modal -->
<div class="modal fade" id="MmyModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="modal-title"> <%= @watching.first.title %> </h4>
      </div>
      <div class="modal-body">
            <div class="modal-body-content"> 
<div class="entry">
<div class="row">
<div class="col-md-2 col-lg-2">
<%= image_tag(@watching.first.picture_url, size: "150x150", class: "media_image") %>
</div>
<div class="col-md-4 col-md-offset-4 col-lg-4">
<%= sanitize(@watching.first.description) %>
</div>
</div>
<div class="estimate_line">
<span class="estimate">Estimate: <%= number_to_currency(@watching.first.estimate) %></span>
</div>
</div>
</div>

    <div class="ajax-loader"></div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Go Back</button>
        
      </div>
    </div>
  </div>
</div>




<!-- Modal -->
<div class="modal fade" id="myModal2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="modal-title"> <%= @watching.second.title %> </h4>
      </div>
      <div class="modal-body">
            <div class="modal-body-content">
<div class="entry">
<div class="row">
<div class="col-md-2 col-lg-2">
<%= image_tag(@watching.second.picture_url, size: "150x150", class: "media_image") %>
</div>
<div class="col-md-4 col-md-offset-4 col-lg-4">
<%= sanitize(@watching.second.description) %>
</div>
</div>
<div class="estimate_line">
<span class="estimate">Estimate: <%= number_to_currency(@watching.second.estimate) %></span>
</div>
</div>

</div>

    <div class="ajax-loader"></div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Go Back</button>

      </div>
    </div>
  </div>
</div>




<!-- Modal -->
<div class="modal fade" id="myModal3" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="modal-title"> <%= @watching.third.title %> </h4>
      </div>
      <div class="modal-body">
            <div class="modal-body-content">
<div class="entry">
<div class="row">
<div class="col-md-2 col-lg-2">
<%= image_tag(@watching.third.picture_url, size: "150x150", class: "media_image") %>
</div>
<div class="col-md-4 col-md-offset-4 col-lg-4">
<%= sanitize(@watching.third.description) %>
</div>
</div>
<div class="estimate_line">
<span class="estimate">Estimate: <%= number_to_currency(@watching.third.estimate) %></span>
</div>
</div>

</div>

    <div class="ajax-loader"></div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Go Back</button>

      </div>
    </div>
  </div>
</div>

app/views/projects/edit.html.erb
<%= render 'shared/page_title', title: "Edit Project" %>

<%= render 'form' %>

<%= link_to 'Show', @project, class: "btn btn-default btn-info" %> |
<%= link_to 'Back', projects_path, class: "btn btn-default btn-warning" %>

app/views/projects/index.html.erb
<%= render 'shared/page_title', title: "All Projects" %>

<%= will_paginate %>

 <% @projects.each do |project| %>
  <div class="row projects">
      
    <div class="col-md-2">
    <section class="project_info center">
       <%= image_tag(project.picture_url, class: 'list_image', size: 50) if project.picture? %>
       <h5><%= project.title %></h5>
     </section>
    </div>

    <div class="col-md-6 well">
       <h4><%= link_to project.title, project_path(project) %></h4> 
       <p><%= truncate(strip_tags(project.description), length: 80) %></p>
        <p>
        <span class='quiet'><small>Created &nbsp&nbsp<%= time_ago_in_words(project.created_at) %> ago &nbsp&nbsp and &nbsp&nbsp Updated <%= time_ago_in_words(project.updated_at) %> ago</small></span>
        </p>
        <div class="pull-right">
          <%= link_to like_project_path(project, like: true), method: :post do %>
            <i class="glyphicon glyphicon-thumbs-up"></i>&nbsp <%= project.thumbs_up_total %>
          <% end %>&nbsp&nbsp&nbsp&nbsp
          <%= link_to like_project_path(project, like: false), method: :post do %>
           <i class="glyphicon glyphicon-thumbs-down"></i>&nbsp <%= project.thumbs_down_total %>
          <% end %>
        </div>
      </div>

     <div class="col-md-4">
      <%#= image_tag(project.picture.url, size: "250x150", class: "media_image") if project.picture? %>
     </div>


    </div>
   <hr/> 
   <% end %>

<%= will_paginate %>

app/views/projects/new.html.erb
<%= render 'shared/page_title', title: "Create New Project" %>

<%= render 'form' %>

<%= link_to 'Return to user profile', user_project_path(id: current_user.id), class: "btn btn-default btn-warning" %>

app/views/projects/show.html.erb
 <div class="row">
  <div class="col-md-6 col-md-offset-2">
   
   <%= render 'shared/page_title', title: @project.title %>  
  </div>
  <div class="col-md-2">
   <% if user_signed_in? and @project.user == current_user %>
    <%= link_to "Edit Project", edit_project_path,  class: "btn btn-lg btn-success" %>
   <% end %>
  </div>
 </div>

   <div class="container entry"> <!--entry-->
    <div class="wells wells-lg"> <!--wells-->
      <div class="row"> <!--media-->
        <div class="col-md-4"><!--media-left-->
         <%= image_tag(@project.picture_url, size: "250x250", class: "media_image") if @project.picture? %>
        </div> <!--media-left-->
        <div class="col-md-7"> <!--media-body-->
         <%= sanitize(@project.description) %>
         <div class="estimate_line"> <!-- estimate-line-->
          <span class="estimate">Estimate: <%= number_to_currency(@project.estimate) %></span>
         </div> <!-- estimate-line -->
  <section class="search-form">
           <%= form_tag pledges_path(project_id: @project.id), method: "post", remote: true do %>
            <div class="input-group input-group-lg"> <!-- input-group-->
           <%= text_field_tag :amount, nil, placeholder:'0.00', id: 'new-todo', class: "form-control input-lg" %>
       <span class="input-group-btn">
           <%= submit_tag 'Make Pledge', class: "btn btn-danger btn-lg" %>
       </span>
       </div><!--input-group-->
           <% end %>
         </section>
           <div class="pull-right">
          <%= link_to like_project_path(@project, like: true), method: :post do %>
            <i class="glyphicon glyphicon-thumbs-up"></i>&nbsp <%= @project.thumbs_up_total %>
          <% end %>&nbsp&nbsp&nbsp&nbsp
          <%= link_to like_project_path(@project, like: false), method: :post do %>
           <i class="glyphicon glyphicon-thumbs-down"></i>&nbsp <%= @project.thumbs_down_total %>
          <% end %>
        </div>
         </div> <!-- media-body -->


       </div> <!--media-->
      </div> <!--wells-->
    </div> <!--entry-->
<hr/>

    <div class="container">
      <div class="row">
      <div class="col-md-2">  
   </div>
       <div class="col-md-9">
      <%= image_tag(@project.picture.url, size: "350x350", class: "media_image") if @project.picture? %>
     </div>
  </div>
 </div>

 <h5><%= link_to "Return to Projects listing", projects_path, class: "btn btn-warning btn-small" %></h5>

app/views/projects/show.js.erb
//$("#MmyModal").html('<%#= j render "projects/show" %>')

var title       =   '.modal-title',
    loader      =   '.ajax-loader',
    content     =   '.modal-body-content',
    dataRemote  =   'a[data-remote=true]',
    toolbar     =   'div.modal-footer',
    modal       =   '#MmyModal';

//i set the title through a helper function
$(title).html('My Messages');
//hides the modal and shows the ajax content
$(loader).fadeToggle('fast', function() {
  $(loader).fadeOut('slow');
  $(content).html('<%= j render("show") %>');
  $(modal).modal();
});
//brings the loader back up + gets rid of the content when linking to another controller method etc
$(content).on('click', dataRemote, function(){
  $(content).fadeOut('slow', function() {
    $(content).empty();
    $(loader).fadeIn('slow');
  });
});