config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  resources :donations
  resources :pledges
  resources :carts
  resources :notes
  get 'charity/index'

  get 'user/:id/profile' => 'user#profile', as: :profile
  get 'user/:id/project' => 'user#project', as: :user_project
  get 'user/:id/donation' => 'user#donation', as: :user_donation

  resources :projects, param: :slug do
    member do
     post 'like'
     get 'who_donated'
    end
  end

    namespace :api do
      namespace :v1 do
        resources :items, only: [:index, :create, :destroy, :update]
      end
    end

  namespace :admin do
   resources :users, except: [:new, :create]
   resources :projects, param: :slug, except: [:new, :create]
   resources :projects, only: [:archive, :unarchive] do
    post :archive
    post :unarchive
    post :faeture
    post :unfaeture
    post :watched
    post :unwatched
  end
  end

    root 'charity#index', as: 'charity'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  has_many :likes
  has_many :projects
  has_many :pledges
  has_many :donations, through: :pledges
  has_many :carts, through: :pledges
  has_many :authorizations

  mount_uploader :picture, PictureUploader

  def self.new_with_session(params,session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"],without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
   end
  end

  def self.from_omniauth(auth, current_user)
    authorization = Authorization.where(:provider => auth.provider, :uid => auth.uid.to_s, :token => auth.credentials.token, :secret => auth.credentials.secret).first_or_initialize
    if authorization.user.blank?
      user = current_user || User.where('email = ?', auth["info"]["email"]).first
      if user.blank?
       user = User.new
       user.password = Devise.friendly_token[0,10]
       user.first_name = auth.info.name
       user.email = auth.info.email
       if auth.provider == "twitter" 
         user.save(:validate => false) 
       else
         user.save
       end
     end
     authorization.username = auth.info.nickname
     authorization.user_id = user.id
     authorization.save
   end
   authorization.user
 end

  def name
   [first_name, last_name].join(" ")
  end


end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
 before_action :set_user, only: [:show, :edit, :update, :destroy]

   # Get /admin/users
  def index
   render locals: { users:  User.all }
  end

    # Get /admin/users/1
  def show
   render locals: { user: @user }
  end
 
   # Get /admin/users/1/edit
  def edit
   render locals: { user: @user }
  end

    # PATCH/PUT /admin/users/1
  def update
   if @user.update(user_params)
     flash[:notice] = "#{@user.name} was successfully updated."
     redirect_to admin_users_path
   else
     render :edit, locals: { user: @user }
   end
  end

    # DELETE /admin/users/1
   def destroy
    user_name = @user.name
    @user.destroy
     flash[:notice] = "#{@user.name} was successfully destroyed."
     redirect_to admin_users_path
   end

  private
   # Use callbacks to share common setup or constraints between actions.

  def set_user
   @user = User.find(params[:id])
  end

   # Only allow a trusted parameter "white list" through
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :featured)
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_filter :set_user, only: [:show, :edit, :update]
  before_filter :validate_authorization_for_user, only: [:edit, :update]

  rescue_from ActiveRecord::RecordNotFound, with: :invalid_path
  
   layout "user_layout"
  def index
   @total_donations = Donation.count
   @pledges = Pledge.all
  end

  def profile
   @pledge = current_user.pledges
  end
  def project
   @project = current_user.projects
  end
  def donation
   @pledge = current_user.pledges
  end
  def show
  end

  private

    def set_user
      @user = User.find(params[:id])
    end

    def validate_authorization_for_user
       redirect_to root_path unless @user == current_user
    end

end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/_form.html.erb
<%= simple_form_for @user do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :first_name, :required => true, :autofocus => true %>
    <%= f.input :username, :required => true %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

<div>
Connect Account



<% ['facebook', 'twitter', 'github', 'linkedin', 'google_oauth2'].each do |provider| %>

  <% if current_user.authorizations.pluck(:provider).include?(provider.to_s) %>
    <%= provider.to_s.titleize %> Connected
  <% else %>
      <%#= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path('user', provider) %>
  <% end %>
<br/>
<% end %>

</div>

app/views/user/_greeting.html.erb
<h1><%= current_user.name %></h1>

app/views/user/donation.html.erb
<%= render 'user/greeting' %>
<% @pledge.each do |user| %>

<%if user.donation %> You made donation with <%=user.donation.pay_type %> <h3>on  <%= user.donation.created_at.strftime("%d/%b/%Y %I:%M %p") %></h3> of <%= number_to_currency(user.amount) %> to the benefit of <%= user.project.title %>
<% end %>

<br/>
<hr/>
    
<% end %>

app/views/user/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %>

app/views/user/index.html.erb
<h1> Welcome <%= current_user.name %> </h1>


<div class="row">

<div class="col-sm-2 col-md-2 user-sidebar">

It's <%= Time.now %>

</div>

<div class="col-sm-9 col-md-8 col-md-offset-1 user-main">
<p>We have <%= pluralize(@total_donations, "donation") %></p>
<p>You have have <%= current_user.pledges.count %> pledges in cart</p>
<div>
<% current_user.pledges.each do |user|%>
<h3> Project Name: <%= user.project.title %></h3>
<h3> Amount Pledged: <%= user.amount %></h3>
<%= button_to "Make Donation", new_donation_path, method: :get %>
<%if user.donation %> You made donation with <%=user.donation.pay_type %> <h3>at: <%= user.donation.created_at %></h3>
<% end %>

<%= user.cart_id %>
<% end %>
</div>
</div>

</div>

app/views/user/profile.html.erb
<%= render 'user/greeting' %>
<hr/>
<div class="well well-default">
<% @pledge.each do |pledge| %>
 You pledged <%= number_to_currency(pledge.amount) %> to <%= link_to pledge.project.title, project_path(pledge) %>  <%= distance_of_time_in_words_to_now pledge.created_at%> ago <% unless pledge.cart_id.nil? %><%= button_to "Make Donation", new_donation_path, method: :get %> <% end %><br/>
<hr/>
<% end %>
</div>

app/views/user/project.html.erb
<h3 class="center">Projects you proposed</h3>
<hr/>

<div class="row col-md-12 pull-right">
<% @project.each do |project| %>

  <div class="entry"> <!--entry-->

   <%# if user_signed_in? and project.user == current_user %>
    <%#= link_to "Edit Project", edit_project_path,  class: "btn btn-lg btn-success" %>
  <%# end %>

    <div class="wells wells-default"> <!--wells-->
      <h2><%= project.title %></h2>
        <p> <%= sanitize(project.description) %></p>

         <div class="estimate_line"> <!-- estimate-line-->
          <span class="estimate">Estimate: <%= number_to_currency(project.estimate) %></span>
         </div> <!-- estimate-line -->
  <section class="search-form">
           <%= form_tag pledges_path(project_id: project.id), method: "post", remote: true do %>
            <div class="input-group input-group-lg"> <!-- input-group-->
           <%= text_field_tag :amount, nil, placeholder:'0.00', id: 'new-todo', class: "form-control input-lg" %>
       <span class="input-group-btn">
           <%= submit_tag 'Make Pledge', class: "btn btn-danger btn-lg" %>
       </span>
       </div><!--input-group-->
           <% end %>
         </section>

           <div class="pull-right">
          <%= link_to like_project_path(project, like: true), method: :post do %>
            <i class="glyphicon glyphicon-thumbs-up"></i>&nbsp <%= project.thumbs_up_total %>
<% end %>&nbsp&nbsp&nbsp&nbsp
          <%= link_to like_project_path(project, like: false), method: :post do %>
           <i class="glyphicon glyphicon-thumbs-down"></i>&nbsp <%= project.thumbs_down_total %>
          <% end %>
        </div>


      </div> <!--wells-->
    </div> <!--entry-->
<hr/>

       <div class="well well-default">
      <%= image_tag(project.picture.url) if project.picture? %>
     </div>

<% end %> <br/>
</div>
<hr/>

app/views/user/show.html.erb
<p>
  <strong>Name:</strong>
	  <%= (image_tag @user.picture_url(:thumb).to_s) %>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %>